// <auto-generated />
namespace DAL_OPDRACHT_PR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitialCommit_GeneratingAllBasicTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCommit_GeneratingAllBasicTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121320080_InitialCommit_GeneratingAllBasicTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
