// <auto-generated />
namespace DAL_OPDRACHT_PR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddingRelationshipBetweenGezinUitgaveTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingRelationshipBetweenGezinUitgaveTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121327264_AddingRelationshipBetweenGezinUitgaveTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
